name: test part
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  linting:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6.0.2
      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

  building:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6.0.2
      - name: Deploy to Production
        run: npm run build
  deploy:
    needs: building
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6.0.2
      - name: Deploy to Production
        run: echo "Deploying to production..."
